[build]
nixpacksVersion = "1.15.0"
[phases.tesseract]
cmds = [
  "apt update",
  "apt install -y tesseract-ocr"
]
dependsOn = ["install"]

[phases.poppler]
cmds = [
  "apt update",
  "apt install -y poppler-utils"
]
dependsOn = ["install"]
